version: 2.1

jobs:
  build:
    docker:
      - image: alpinelinux/build-base:latest
        steps:
        - checkout
        - run: echo "$ABUILD_PRIVATE_KEY" | base64 -d > ~/.abuild/alpine-infra@lists.alpinelinux.org-64a7437f.rsa
        - run: echo "$ABUILD_PUBLIC_KEY" | base64 -d > ~/.abuild/alpine-infra@lists.alpinelinux.org-64a7437f.rsa.pub
        - run: echo "$ABUILD_PUBLIC_KEY" | base64 -d > /etc/apk/keys/alpine-infra@lists.alpinelinux.org-64a7437f.rsa.pub
        - run: echo 'PACKAGER_PRIVKEY="/home/buildozer/.abuild/alpine-infra@lists.alpinelinux.org-64a7437f.rsa"' >> ~/.abuild/abuild.conf
        - run: find testing -type d -exec /bin/sh -c 'cd {}; abuild -r' \;
        - run: git checkout -- . && git clean -fd && git checkout -b gh-pages
        - run: cp -r ~/packages .
        - run: git add . && git commit -m "Update packages"
        - run: 'git push gh-pages https://x-access-token:"$GITHUB_TOKEN"@$(git remote get-url --push origin | cut -d@ -f 2 | tr : /) HEAD:refs/heads/gh-pages'
workflows:
  build:
    jobs:
      - build

