version: 2.1

jobs:
  build:
    docker:
      - image: alpinelinux/build-base:latest
    steps:
      - run: doas apk add --no-cache git openssh
      - checkout
      - run: make
workflows:
  build:
    jobs:
      - build:
        filters:
          branches:
            only: ["main"]
